# Generated by Django 6.1.1 on 2026-09-25 19:48

import apps.nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, validators=[apps.nodes.models.is_valid_name])),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('NotReady', 'NotReady'), ('Cordoned', 'Cordoned'), ('Draining', 'Draining')], default='NotReady', max_length=10)),
                ('cpu_capacity', models.PositiveIntegerField(help_text='CPU capacity in millicores (m). For example, 1000m = 1 CPU core.')),
                ('memory_capacity', models.PositiveBigIntegerField(help_text='Memory capacity in bytes. For example, 1073741824 bytes = 1 GiB.')),
                ('allocable', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('unschedulable', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('resource_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
