# Generated by Django 6.1.1 on 2026-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='allocable',
            new_name='allocatable',
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('NotReady', 'NotReady'), ('Cordoned', 'Cordoned'), ('Draining', 'Draining'), ('Unknown', 'Unknown')], default='NotReady', max_length=10),
        ),
    ]
